export const FETCH_INITIAL_COMPETANCY_SUCESS =
  "FETCH_INITIAL_COMPETANCY_SUCESS";
export const FETCH_INITIAL_COMPETANCY_FAILURE =
  "FETCH_INITIAL_COMPETANCY_FAILURE";
export const UPDATE_COMPETANCY_WEIGHT = "UPDATE_COMPETANCY_WEIGHT";

export const SAVE_COMPETANCY_SUCESS = "SAVE_COMPETANCY_SUCESS";
export const SAVE_COMPETANCY_FAILURE = "SAVE_COMPETANCY_FAILURE";

export const LOADING_COMPETANCY = "LOADING_COMPETANCY";

export const FETCH_PERSONALDEV_COMP_SUCCESS = "FETCH_PERSONALDEV_COMP_SUCCESS";
export const FETCH_PERSONALDEV_COMP_FAILURE = "FETCH_PERSONALDEV_COMP_FAILURE";
