export const FETCH_INITIAL_COMPETANCY_SUCESS = 'FETCH_INITIAL_COMPETANCY_SUCESS';
export const FETCH_INITIAL_COMPETANCY_FAILURE = 'FETCH_INITIAL_COMPETANCY_FAILURE';
export const UPDATE_COMPETANCY_WEIGHT = 'UPDATE_COMPETANCY_WEIGHT';