export const FETCH_BASICINFO_REQUEST = 'FETCH_BASICINFO_REQUEST';
export const FETCH_BASICINFO_SUCCESS = 'FETCH_BASICINFO_SUCCESS';
export const FETCH_BASICINFO_FAILURE = 'FETCH_BASICINFO_FAILURE';

export const EMAIL_VALIDATION_REQUEST = 'EMAIL_VALIDATION_REQUEST';
export const EMAIL_VALIDATION_SUCCESS = 'EMAIL_VALIDATION_SUCCESS';
export const EMAIL_VALIDATION_FAILURE = 'EMAIL_VALIDATION_FAILURE';
